### ISSUE TITLE
[BUG] can't install libndk

### ISSUE THREAD

**Issue by cogumelodogit** [Tanvir1337x/waydroid_tweaks#8]
? Select Android version Android 11
? Please select an action Install
? Select apps ['libndk']
Traceback (most recent call last):
  File "/home/user/Documents/waydroid_tweaks/main.py", line 390, in <module>
    main()
  File "/home/user/Documents/waydroid_tweaks/main.py", line 386, in main
    interact()
  File "/home/user/Documents/waydroid_tweaks/main.py", line 266, in interact
    install_app(args)
  File "/home/user/Documents/waydroid_tweaks/main.py", line 123, in install_app
    args.app, args.android_version, args.microg_variant, args.ca_cert_file
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'microg_variant'

**Comment by Tanvir1337x** [comment]
@cogumelodogit Can you try again now? If you find any more issues let me know.
